USE MASTER
GO

IF DB_ID('TiendaNexus') IS NOT NULL
	DROP DATABASE TiendaNexus
GO

CREATE DATABASE TiendaNexus
GO

USE TiendaNexus
GO

CREATE TABLE CATEGORIA(
  ID_CATEGORIA    CHAR(4)      NOT NULL   PRIMARY KEY,
  DESCRIPCION     VARCHAR(50)  NOT NULL
)

CREATE TABLE USUARIO(
  ID_USUARIO     CHAR(5)       NOT NULL   PRIMARY KEY,
  NOM_USUARIO    VARCHAR(30)   NOT NULL,
  APE_USUARIO    VARCHAR(30)   NOT NULL,
  FECH_REGISTRO  DATE          NOT NULL,
  CORREO_USUARIO VARCHAR(50)   NOT NULL
)

CREATE TABLE TRABAJADORES(
  ID_DNI         CHAR(8)       NOT NULL,
  SALARIO        MONEY         NOT NULL,
  PUESTO         VARCHAR(20)   NOT NULL,
  NOMBRE         VARCHAR(30)   NOT NULL,
  DIRECCION      VARCHAR(40)   NOT NULL,
  DNI_SUPERVISOR CHAR(8)       NOT NULL   REFERENCES TRABAJADORES,
  PRIMARY KEY(ID_DNI)
)

CREATE TABLE AUTOR(
  ID_AUTOR       CHAR(4)       NOT NULL   PRIMARY KEY,
  NOM_AUTOR      VARCHAR(50)   NOT NULL, 
  APE_AUTOR      VARCHAR(40)   NOT NULL,
  NACIONALIDAD   VARCHAR(20)   NOT NULL,
)

CREATE TABLE LIBRO(
  ID_LIBRO       CHAR(5)       NOT NULL   ,
  ID_CATEGORIA   CHAR(4)       NOT NULL   REFERENCES CATEGORIA,
  NOM_LIBRO      VARCHAR(50)   NOT NULL, 
  FECH_LANZAMIENTO DATE        NOT NULL, 
  ID_AUTOR       CHAR(4)       NOT NULL   REFERENCES AUTOR,
  ID_DNI         CHAR(8)       NOT NULL   REFERENCES TRABAJADORES,
  PRIMARY KEY(ID_LIBRO)
)

CREATE TABLE PRESTAMO(
  ID_PRESTAMO   CHAR(4)         NOT NULL  ,
  ID_USUARIO    CHAR(5)         NOT NULL  REFERENCES USUARIO,
  FECH_PRESTAMO DATE            NOT NULL,
  ID_DNI        CHAR(8)         NOT NULL  REFERENCES TRABAJADORES,
  PRIMARY KEY(ID_PRESTAMO)
)

CREATE TABLE LIBRO_PRESTAMO(
  ID_LIBRO     CHAR(5)          NOT NULL   REFERENCES LIBRO,
  ID_PRESTAMO  CHAR(4)          NOT NULL  REFERENCES PRESTAMO,
  FECHA_DEVOLUCION DATE         NOT NULL ,
  PRIMARY KEY(ID_LIBRO,ID_PRESTAMO)
)

CREATE TABLE LIMPIEZA(
  ID_DNI      CHAR(8)           NOT NULL  REFERENCES TRABAJADORES,
  HAB_ESPECIFICA  VARCHAR(40)   NOT NULL,
  HORARIO     DATE              NOT NULL
  PRIMARY KEY(ID_DNI)
)

CREATE TABLE RECEPCIONISTA(
  ID_DNI      CHAR(8)           NOT NULL  REFERENCES TRABAJADORES,
  CORREO      VARCHAR(40)       NOT NULL,
  CONOC_INFORMATICO VARCHAR(40) NOT NULL
  PRIMARY KEY(ID_DNI)
)

