IF DB_ID('BD_MAQUINARIAS')IS NOT NULL
DROP DATABASE BD_MAQUINARIAS
GO

CREATE DATABASE BD_MAQUINARIAS
ON(
NAME=BD_MAQUINARIAS_PRI,
FILENAME='C:\MAQUINARIAS\DATA.MDF',
SIZE=10MB,
MAXSIZE=100MB,
FILEGROWTH=10%

),(
NAME=BD_MAQUINARIAS_SEC,
FILENAME='C:\MAQUINARIAS\DATA.NDF',
SIZE=5MB,
MAXSIZE=50MB,
FILEGROWTH=10%
)
LOG ON(
NAME=BD_MAQUINARIAS_TRA,
FILENAME='C:\MAQUINARIAS\DATA.LDF',
SIZE=5MB,
MAXSIZE=40MB,
FILEGROWTH=10%

)

GO

SP_HELPDB BD_MAQUINARIAS
GO


ALTER DATABASE BD_MAQUINARIAS
   MODIFY FILE(
   NAME='BD_MAQUINARIAS_TRA',
   SIZE=10,
   FILEGROWTH=15%
   
   )
   GO


ALTER DATABASE BD_MAQUINARIAS
 ADD FILE(
  NAME='BD_MAQUINARIAS1',
  FILENAME='C:\MAQUINARIAS\SEC\BD_MAQUINARIAS1.NDF',
  SIZE=5,
  MAXSIZE=20,
  FILEGROWTH=10%)
 GO
 ALTER DATABASE BD_MAQUINARIAS
ADD FILE (
NAME='BD_MAQUINARIAS2',
FILENAME='C:\MAQUINARIAS\SEC\BD_MAQUINARIAS2.NDF',
SIZE=5,
MAXSIZE=20,
FILEGROWTH=10%
)
GO
ALTER DATABASE BD_MAQUINARIAS
ADD FILE (
NAME='BD_MAQUINARIAS3',
FILENAME='C:\MAQUINARIAS\SEC\BD_MAQUINARIAS3.NDF',
SIZE=5,
MAXSIZE=20,
FILEGROWTH=10%
)
GOALTER DATABASE BD_MAQUINARIASREMOVE FILE BD_MAQUINARIAS2










