IF DB_ID ('BD_INSTITUTO') IS NOT NULL
DROP DATABASE BD_INSTITUTO
GO
CREATE DATABASE BD_INSTITUTO
ON (
NAME='BD_INSTITUTO_PRI',
FILENAME='C:\INSTITUTO\DATOS\BD_INSTITUTO.MDF',
SIZE=20MB,
MAXSIZE=200MB,
FILEGROWTH=8MB
)
LOG ON(
NAME='BD_INSTITUTO_TRA',
FILENAME='C:\INSTITUTO\TRANS\BD_INSTITUTO.LDF',
SIZE=12MB,
MAXSIZE=150MB,
FILEGROWTH=15% 
)
GO


SP_HELPDB BD_INSTITUTO

ALTER DATABASE BD_INSTITUTO
ADD FILE(
NAME='BD_INSTITUTO_SEC1',
FILENAME='C:\INSTITUTO\SECUNDARIO\BD_INSTITUTO_SEC1.NDF',
SIZE=2MB,
MAXSIZE=70MB,
FILEGROWTH=7% 
),
(
NAME='BD_INSTITUTO_SEC2',
FILENAME='C:\INSTITUTO\SECUNDARIO\BD_INSTITUTO_SEC2.NDF',
SIZE=2MB,
MAXSIZE=70MB,
FILEGROWTH=7% 
),
(
NAME='BD_INSTITUTO_SEC3',
FILENAME='C:\INSTITUTO\SECUNDARIO\BD_INSTITUTO_SEC3.NDF',
SIZE=2MB,
MAXSIZE=70MB,
FILEGROWTH=7% 
)
GO

ALTER DATABASE BD_INSTITUTO
  MODIFY FILE(
  NAME='BD_INSTITUTO_TRA',
  SIZE=20MB,
  MAXSIZE=180MB,
  FILEGROWTH=18%
  )

  ALTER DATABASE BD_INSTITUTO
  REMOVE FILE BD_INSTITUTO_SEC2
  GO
